name: Publish to NPM

on:
  push:
    tags:
      - 'tools@*'
      - 'pkg@*'
      - 'release@*'
      - 'cli@*'
      - 'polyfill@*'
      - 'storage@*'
      - 'logger@*'
      - 'scripts@*'
      - 'napi@*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-napi:
    if: github.repository == 'baicie/tools' && startsWith(github.ref_name, 'napi')
    name: Build bindings and node packages
    uses: ./.github/workflows/reusable-release-build.yml

  publish-napi:
    needs: build-napi
    if: github.repository == 'baicie/tools' && startsWith(github.ref_name, 'napi')
    name: Publish npm Packages
    runs-on: ubuntu-latest
    permissions:
      id-token: write # for `npm publish --provenance`
    steps:
      - uses: taiki-e/checkout-action@b13d20b7cda4e2f325ef19895128f7ff735c0b3d # v1.3.1

      - uses: oxc-project/setup-node@141eb77546de6702f92d320926403fe3f9f6a6f2 # v1.0.5

      - name: Git Reset Hard
        run: git reset --hard # fix pnpm install add new line for package.json

      - name: Download Binding Artifacts
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          path: packages/napi/artifacts

      - name: Create @baicie/napi/npm dirs
        run: pnpm --filter @baicie/napi exec napi create-npm-dirs

      - name: Move Binding Artifacts
        run: pnpm --filter @baicie/napi artifacts

      - name: List Napi Bindings
        run: ls -R ./packages/napi/npm
        shell: bash

      - name: Download Node Artifacts
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          path: packages/napi/dist
          name: node-artifact

      - name: Download `@baicie/napi-browser` Artifacts
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          path: packages/napi-browser/dist
          name: browser-artifact

      - name: Publish(Dry Run)
        run: |
          pnpm publish -r --tag latest --dry-run --no-git-checks

      - name: Publish
        run: |
          npm i -g npm
          pnpm publish -r --tag latest --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

  publish:
    if: github.repository == 'baicie/tools' && !startsWith(github.ref_name,'napi')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: Set node version to 24
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
          # disable cache, to avoid cache poisoning (https://docs.zizmor.sh/audits/#cache-poisoning)
          package-manager-cache: false

      - name: Disallow installation scripts
        run: yq '.onlyBuiltDependencies = []' -i pnpm-workspace.yaml

      - name: Install deps
        run: pnpm install
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'

      - name: Publish package
        run: npm i -g npm && pnpm run ci-publish "$REF_NAME"
        env:
          REF_NAME: ${{ github.ref_name }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
