name: Other Test

permissions: {}

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      changed:
        required: true
        type: boolean

jobs:
  unit-test:
    if: ${{ inputs.changed }}
    name: Unit Test
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          submodules: true # Pull submodules for additional files
          persist-credentials: false

      - uses: oxc-project/setup-node@141eb77546de6702f92d320926403fe3f9f6a6f2 # v1.0.5

      - name: Build
        run: pnpm build

      - name: Run unit tests
        run: pnpm run test-unit

  lint-and-test-dts:
    if: ${{ inputs.changed }}
    name: Lint and Test DTS
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          submodules: true # Pull submodules for additional files
          persist-credentials: false
      - uses: oxc-project/setup-node@141eb77546de6702f92d320926403fe3f9f6a6f2 # v1.0.5

      - run: pnpm build

      - name: Run eslint
        run: pnpm run lint

      - name: Run prettier
        run: pnpm run format-check

      - name: Run tsc
        run: pnpm run check

      - name: Run docs
        run: pnpm run docs-build
